---

- name: Ensure Xresources.d directory exists
  file:
    path: "{{ ansible_env.HOME }}/.Xresources.d"
    state: directory

- name: Upload Xresources file
  copy:
    src: dot-Xresources
    dest: "{{ ansible_env.HOME }}/.Xresources"

- name: Upload Xresources.d files
  file:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.Xresources.d/"
  loop:
    - "colors"
    - "fonts-file"
    - "rxct-unicode"

- name: Upload xinitrc file
  copy:
    src: dot-xinitrc
    dest: "{{ ansible_env.HOME }}/.xinitrc"

- name: Ensure local folders are present
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ansible_env.HOME }}/.local/share/fonts/"
    - "{{ ansible_env.HOME }}/go"
    - "{{ ansible_env.HOME }}/go/bin"
    - "{{ ansible_env.HOME }}/go/pkg"
    - "{{ ansible_env.HOME }}/go/src"

- name: Upload fonts  # TODO: Download fonts from JetBrains' github to get newest version
  copy:
    src: fonts/
    dest: "{{ ansible_env.HOME }}/.local/share/fonts/"

- name: Ensure wallpaper is present
  copy:
    src: wallpaper.png
    dest: "{{ ansible_env.HOME }}/.wallpaper.png"

- name: Ensure wallpaper is in use
  shell: gsettings set org.gnome.desktop.background picture-uri {{ ansible_env.HOME }}/.wallpaper.png

- name: Ensure urxvt is default terminal
  shell: gsettings set org.gnome.desktop.default-applications.terminal exec urxvt
