---
- name: Ensure Vim is installed
  become: yes
  pacman:
    name: gvim
    state: present
    update_cache: yes

- name: Ensure all folders are persent
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "users"
  loop:
    - ".vim"
    - ".vim/undo"
    - ".vim/swap"
    - ".vim/autoload"
    - ".vim/UltiSnips"
    - ".config/nvim"

- name: Get vim-plug
  get_url: url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim dest={{ ansible_env.HOME }}/.vim/autoload/plug.vim

- name: Upload vim configuration file
  copy:
    src: dot-vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"
    owner: "{{ ansible_user }}"
    group: "users"

- name: Upload nvim init configuration file
  copy:
    src: init.vim
    dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"
    owner: "{{ ansible_user }}"
    group: "users"
